eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:https://eurekaserver-production-adff.up.railway.app/eureka/}
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}

spring:
  application:
    name: ${APP_NAME:clientes}

server:
  port: ${PORT:8080}
